# After a release is successfully published, upload oranda-config-schema.json to it
name: Release - Config Schema

# We're going to edit a gh release, so we need that permission
permissions:
  contents: write

on:
  # Whenever a workflow called "Release" completes, run this!
  workflow_run:
    workflows: ["Release"]
    types:
        - completed

# Alright, let's do it!
jobs:
  web:
    name: Add schema to release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # We get the tag of the release in github.event.workflow_run.head_branch
      # No idea why it's stored there with that name, but, it is?
      - name: Install oranda and upload schema
        run: |
          echo "uploading schema to ${{ github.event.workflow_run.head_branch }}"
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/oranda/releases/download/${{ github.event.workflow_run.head_branch }}/oranda-installer.sh | sh
          oranda config-schema > oranda-config-schema.json 
          gh release upload ${{ github.event.workflow_run.head_branch }} oranda-config-schema.json